alias clear2='clear && clear'
alias test='./run_tests'
alias c='clear'
alias x='exit'
alias q='exit'
alias quit='exit'
alias simon_says='sudo'
alias doc='cd && cd Documents/'
alias po='sudo poweroff'
alias giveup='~/giveup'
alias CD='cd'
alias CLEAR='clear'
alias LS='ls'

